replicaCount: 1

labels:
  app: foundation-api

development:
  enabled: false

image:
  repository: ""
  pullPolicy: Always
  tag: "latest"

config:
  host: ""
  port: ""
  postgres:
    host:
    port: 5432
    database:
    user:
    pool_min_size: 1
    pool_max_size: 5
  kafka:
    cluster_host: ""
  secret_key: ""
    
imagePullSecrets: []

serviceAccount:
  create: false
  annotations: {}
  name: "default"

podAnnotations: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: ImplementationSpecific

resources: {}

livenessProbe:
  initialDelaySeconds: 10
  httpGet:
    path: /api/.well-known/status
    port: 9000
    periodSeconds: 10
readinessProbe:
  initialDelaySeconds: 60
  tcpSocket:
    port: 9000
    periodSeconds: 10

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

vpa:
  enabled: ""
  updateMode: "Auto"
  minAllowed:
    cpu: "100m"
    memory: "128Mi"
  maxAllowed:
    cpu: "800m"
    memory: "512Mi"

pdb:
  enabled: true
  maxUnavailable: "50%"
  selector:
    app: backend

nodeSelector: {}

tolerations: []

affinity: {}
