apiVersion: v2
name: hive-metastore
description: A Helm chart to deploy hive-metastore
type: application
version: 1.1.2
appVersion: 1.1.2
keywords:
    - hive-metastore
home: https://github.com/apache/hive
icon: https://hive.apache.org/images/hive_logo_medium.jpg
sources:
    - https://github.com/apache/hive
    - https://github.com/meshxdata/hive-metastore
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    version: ~15.2.1
    repository: https://charts.bitnami.com/bitnami