replicaCount: 1

# set this to use an existing secret rather than generate one
existingSecret:

istio:
  enabled: false


config:
  host: 0.0.0.0
  port: 65433
  postgres:
    host: ""
    port: 5432
    database: "" 
    user: ""
    pool_min_size: 1
    pool_max_size: 5


  kafka:
    cluster_host: ""

  events:
    openlineage_spark_topic: ""
    foundation_events_topic: ""
    foundation_profiling_topic: ""
    foundation_validations_topic: ""
    foundation_classification_topic: ""
    foundation_notifications_topic: ""

image:
  repository: ""
  pullPolicy: Always
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: "default"

podSecurityContext:
  fsGroup: 2000
  runAsNonRoot: true
  runAsUser: 1000

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 65433

ingress:
  enabled: false

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80


livenessProbe:
  initialDelaySeconds: 10
  tcpSocket:
    port: 65432
    port: 65432
    periodSeconds: 10
readinessProbe:
  initialDelaySeconds: 60
  tcpSocket:
    port: 65432
    periodSeconds: 10