apiVersion: v1
kind: ConfigMap
metadata:
  name: foundation-watcher
data:
  MX_HOST_BIND: "{{ .Values.config.host }}"
  MX_PORT_BIND: "{{ .Values.config.port }}"
  MX_POSTGRES_HOST: "{{ .Values.config.postgres.host }}"
  MX_POSTGRES_PORT: "{{ .Values.config.postgres.port }}"
  MX_POSTGRES_DATABASE: "{{ .Values.config.postgres.database }}"
  MX_POSTGRES_USER: "{{ .Values.config.postgres.user }}"
  MX_POSTGRES_POOL_MIN_SIZE: "{{ .Values.config.postgres.pool_min_size }}"
  MX_POSTGRES_POOL_MAX_SIZE: "{{ .Values.config.postgres.pool_max_size }}"
  MX_KAFKA_CLUSTER_HOST: "{{ .Values.config.kafka_cluster_host }}"
  MX_EVENTS_KAFKA_TOPIC: "{{ .Values.config.events_kafka_topic }}"
  MX_DEBUG: "false"
  MX_ENV: "development"
  MX_RELEASE_TAG: "latest"
  MX_EXTERNAL_HOST: "localhost"
  MX_API_PREFIX: "/api"
  MX_LOGGING_LEVEL: "debug"
  