{{- if (include "chart.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: foundation-watcher
data:
  MX_POSTGRES_PASSWORD: "{{ .Values.config.postgres.password | b64enc }}"
{{- end -}}
