apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "chart.serviceAccountName" . }}-clusterrolebinding
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: {{ include "chart.serviceAccountName" . }}-clusterrole
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ include "chart.serviceAccountName" . }}
