{{- if eq (include "chart.createExternalSecret" .) "false" }}
{{- if (include "chart.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: foundation-processor
data:
  MX_POSTGRES_PASSWORD: "{{ .Values.config.postgres.password | b64enc }}"
  MX_SECRET_ACCESS_KEY: "{{ .Values.config.hub.secret_access_key | b64enc }}"
{{- end -}}
{{- end -}}
