apiVersion: v1
entries:
  backend:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-11-04T16:02:49.320705+01:00"
    description: A Helm chart for Kubernetes
    digest: a7d1c63c5c845098b6b46da9bc44a85b3b29a7078ba6ba5a8c88ed4ca3f228ce
    name: backend
    type: application
    urls:
    - backend-0.1.0.tgz
    version: 0.1.0
  processor:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2024-11-04T16:02:49.321265+01:00"
    description: A Helm chart for the core event processor API
    digest: 6a271f0880ae79ed44652c663b80f19dad59afd20d1d93d4b31988667d903fe6
    name: processor
    type: application
    urls:
    - processor-0.0.1.tgz
    version: 0.0.1
  watcher:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-11-04T16:02:49.321685+01:00"
    description: A Helm chart for Kubernetes
    digest: 7b3bda7586e9d09537ce8057f92b2cedeadd91f3915a59ccbfbd2691ecd812db
    name: watcher
    type: application
    urls:
    - watcher-0.1.0.tgz
    version: 0.1.0
generated: "2024-11-04T16:02:49.318362+01:00"
