{{- if eq (include "chart.createExternalSecret" .) "true" }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: foundation-processor
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  refreshInterval: 33m
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore
  target:
    name: foundation_processor-processor
    creationPolicy: Owner
    template:
      metadata:
        labels:
        {{- include "chart.labels" . | nindent 10 }}
        annotations:
  data:
  - secretKey: MX_POSTGRES_PASSWORD
    remoteRef:
      key: "core.{{ .Values.config.externalSecret.coreName }}.foundation_processor-processor.nc_postgres_password"
  - secretKey: MX_SECRET_ACCESS_KEY
    remoteRef:
      key: "core.{{ .Values.config.externalSecret.coreName }}.gateway.nc_secret_access_key"
{{- end -}}
