apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.serviceAccountName" . }}-clusterrole
rules:
  - apiGroups: ["", "batch", "extensions"]
    resources: ["pods", "jobs"]
    verbs: ["get", "watch", "list"] # Action required by the initContainer to wait for Kafka and migrations to be initialized
