apiVersion: v1
kind: ConfigMap
metadata:
  name: foundation-backend
data:
MX_API_PREFIX: "/api"
MX_DEBUG: "true"
MX_ENV: "development"
MX_EVENTS_KAFKA_TOPIC: "events"
MX_EXTERNAL_HOST: "backend.foundation.svc.cluster.local"
MX_HOST_BIND: "{{ .Values.config.host }}"
MX_IDENTIFIER: "backend"
MX_KEYCLOAK_CLIENT_ID: "backend"
MX_KEYCLOAK_CLIENT_SECRET: "secret"
MX_KEYCLOAK_ENABLED: "false"
MX_KEYCLOAK_HOST: "keycloak.keycloak.svc.cluster.local"
MX_KEYCLOAK_REALM: "master"
MX_KAFKA_CLUSTER_HOST: "foundation-kafka-kafka-bootstrap:9092"
MX_LOGGING_LEVEL: "DEBUG"
MX_POSTGRES_DATABASE: "{{ .Values.config.postgres.database }}"
MX_POSTGRES_HOST: "{{ .Values.config.postgres.host }}"
MX_POSTGRES_PORT: "{{ .Values.config.postgres.port }}"
MX_POSTGRES_POOL_MAX_SIZE: "{{ .Values.config.postgres.pool_max_size }}"
MX_POSTGRES_POOL_MIN_SIZE: "{{ .Values.config.postgres.pool_min_size }}"
MX_POSTGRES_USER: "{{ .Values.config.postgres.user }}"
MX_PROCESSOR_HOST: "processor.foundation.svc.cluster.local"
MX_PROCESSOR_PORT: "80"
MX_RELEASE_TAG: "latest"
MX_SECRET_KEY: "secret"
MX_TIMING_LOG_LEVEL: "DEBUG"
MX_TRINO_HOST: "trino.trino.svc.cluster.local"
MX_TRINO_PORT: "80"
MX_WATCHER_HOST: "watcher.foundation.svc.cluster.local"
MX_WATCHER_PORT: "80"
MX_PORT_BIND: "{{ .Values.config.port }}"

