apiVersion: v1
kind: ConfigMap
metadata:
  name: foundation-backend
data:
  MX_HOST_BIND: "{{ .Values.config.host }}"
  MX_PORT_BIND: "{{ .Values.config.port }}"
  MX_POSTGRES_HOST: "{{ .Values.config.postgres.host }}"
  MX_POSTGRES_PORT: "{{ .Values.config.postgres.port }}"
  MX_POSTGRES_DATABASE: "{{ .Values.config.postgres.database }}"
  MX_POSTGRES_USER: "{{ .Values.config.postgres.user }}"
  MX_POSTGRES_POOL_MIN_SIZE: "{{ .Values.config.postgres.pool_min_size }}"
  MX_POSTGRES_POOL_MAX_SIZE: "{{ .Values.config.postgres.pool_max_size }}"
  MX_DEBUG: "true"
  MX_ENV: "development"
  MX_RELEASE_TAG: "latest"
  MX_EXTERNAL_HOST: "localhost"
  MX_API_PREFIX: "/api"
  MX_LOGGING_LEVEL: "DEBUG"
  MX_TIMING_LOG_LEVEL: "DEBUG"
  MX_IDENTIFIER: "backend"
  MX_PROCESSOR_HOST: "localhost"
  MX_PROCESSOR_PORT: "8080"
  MX_WATCHER_HOST: "localhost"
  MX_WATCHER_PORT: "8080"
  MX_TRINO_HOST: "localhost"
  MX_TRINO_PORT: "8080"
  MX_KAFKA_CLUSTER_HOST: "localhost"
  MX_EVENTS_KAFKA_TOPIC: "events"
  MX_SECRET_KEY: "secret"
  MX_KEYCLOAK_ENABLED: "false"
  MX_KEYCLOAK_HOST: "localhost"
  MX_KEYCLOAK_REALM: "master"
  MX_KEYCLOAK_CLIENT_ID: "backend"
  MX_KEYCLOAK_CLIENT_SECRET: "secret"
