{{- if .Values.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "chart.fullname" . }}
  updatePolicy:
    updateMode: "{{ .Values.vpa.updateMode }}"
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        minAllowed:
          cpu: "{{ .Values.vpa.minAllowed.cpu }}"
          memory: "{{ .Values.vpa.minAllowed.memory }}"
        maxAllowed:
          cpu: "{{ .Values.vpa.maxAllowed.cpu }}"
          memory: "{{ .Values.vpa.maxAllowed.memory }}"
        controlledValues: "{{ .Values.vpa.controlledValues }}"
{{- end }}