{{- if and ( and .Values.objectStore.minio.accessKey .Values.objectStore.minio.secretKey ) ( not .Values.objectStore.minio.existingSecret ) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hive-metastore.name" . }}-minio-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hive-metastore.labels" $ | trim | nindent 4 }}
type: Opaque
stringData:
  MINIO_ACCESS_KEY: {{ .Values.objectStore.minio.accessKey }}
  MINIO_SECRET_ACCESS_KEY: {{ .Values.objectStore.minio.secretKey }}
{{- end }}

---
{{- if not .Values.postgresql.enabled -}}
{{- if and ( and .Values.externalDatabase.username .Values.externalDatabase.password ) ( not .Values.externalDatabase.existingSecret ) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hive-metastore.name" . }}-externaldb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hive-metastore.labels" $ | trim | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.externalDatabase.username }}
  password: {{ .Values.externalDatabase.password }}
{{- end }}
{{- end }}