{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hive-metastore.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "hive-metastore.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "hive-metastore.serviceAccountName" . }}-role
rules:
  - apiGroups: ["batch", "extensions", ""]
    resources: ["jobs", "pods"]
    verbs: ["get", "list", "watch",] # enabling wait for initDatabase job to complete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "hive-metastore.serviceAccountName" . }}-binding
roleRef:
  apiGroup: ""
  kind: Role
  name: {{ include "hive-metastore.serviceAccountName" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "hive-metastore.serviceAccountName" . }}
{{- end }}