apiVersion: v1
kind: Service
metadata:
  name: {{ include "hive-metastore.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hive-metastore.labels" $ | trim | nindent 4 }}
spec:
  type: {{ .Values.hiveMetastore.service.type }}
  ports:
  - port: {{ .Values.hiveMetastore.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "hive-metastore.selectorLabels" . | nindent 4 }}
